### ISSUE TITLE
Email validator new function

### ISSUE THREAD

**Issue by ayush3160** [suryapratapsinghsuryavanshi/solverjs#30]
Hi @suryapratapsinghsuryavanshi, I think we can add a new email validator function just like the mobile number validator. Let me know If this functionality is needed I can work on it.

**Comment by suryapratapsinghsuryavanshi** [comment]
Hello @ayush3160, interesting. Yes, we always need this type of functionality in SolverJs.

**Comment by ayush3160** [comment]
@suryapratapsinghsuryavanshi Great, I'll start working on this issue can you assign this issue to me. And I was getting one doubt in which folder I should make this function.

**Comment by suryapratapsinghsuryavanshi** [comment]
@ayush3160 Okay, I will assign this issue to you, you can add this method to the utils directory. Please make sure all the code coverage full fill, and refer to any one of the methods from utils.

**Comment by ayush3160** [comment]
@suryapratapsinghsuryavanshi I have made a pull request please have a look. Let me know if any changes are required.

**Comment by suryapratapsinghsuryavanshi** [comment]
Thank You, @ayush3160
